platform :ios, '13.0'
use_frameworks!

target 'CT-PL-Pn-Integration' do
  pod 'CleverTap-iOS-SDK'
  pod 'Plotline'
end

target 'NotificationServiceExtension' do
  pod 'CTNotificationService'
  pod 'Plotline'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
